// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEhDatgl1aN1stt6EJx1WYvVeenirBtIs',
    appId: '1:316075930320:web:eb742b216e41aba64fa4d5',
    messagingSenderId: '316075930320',
    projectId: 'student-directory-2df7c',
    authDomain: 'student-directory-2df7c.firebaseapp.com',
    storageBucket: 'student-directory-2df7c.firebasestorage.app',
    measurementId: 'G-6VP2FPDTKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9uukCd-SQoiyyBox0uqgUitpmJbXkQ_Q',
    appId: '1:316075930320:android:3cf3c82cc5ea42594fa4d5',
    messagingSenderId: '316075930320',
    projectId: 'student-directory-2df7c',
    storageBucket: 'student-directory-2df7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PiRmFDwSh2pJUztAn36oOfDCqgnb78U',
    appId: '1:316075930320:ios:9a40c61eed7103b04fa4d5',
    messagingSenderId: '316075930320',
    projectId: 'student-directory-2df7c',
    storageBucket: 'student-directory-2df7c.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PiRmFDwSh2pJUztAn36oOfDCqgnb78U',
    appId: '1:316075930320:ios:9a40c61eed7103b04fa4d5',
    messagingSenderId: '316075930320',
    projectId: 'student-directory-2df7c',
    storageBucket: 'student-directory-2df7c.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEhDatgl1aN1stt6EJx1WYvVeenirBtIs',
    appId: '1:316075930320:web:2c797d2bba5651904fa4d5',
    messagingSenderId: '316075930320',
    projectId: 'student-directory-2df7c',
    authDomain: 'student-directory-2df7c.firebaseapp.com',
    storageBucket: 'student-directory-2df7c.firebasestorage.app',
    measurementId: 'G-C9EHWL2YZV',
  );
}
